package usecase

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/diegojromerolopez/noctifab/pkg/domain"
)

// ValidatePlannedTasks checks if the Planner Agent provided enough task details
func ValidatePlannedTasks(tasks []domain.Task) error {
	if len(tasks) == 0 {
		return fmt.Errorf("planning failed: no tasks were generated by the planner agent")
	}
	for _, task := range tasks {
		if task.Title == "" || len(task.Description) < 15 {
			return fmt.Errorf("planning failed: task '%s' ('%s') does not have a detailed title or description", task.ID, task.Title)
		}
		if len(task.TargetFiles) == 0 {
			return fmt.Errorf("planning failed: task '%s' ('%s') has no target files specified. The planner agent must always specify the files to be targeted/created", task.ID, task.Title)
		}
	}
	return nil
}

// RunReaderPhase runs the pre-step to collect workspace context before execution
func (o *Orchestrator) RunReaderPhase(ctx context.Context, role string, task domain.Task, state *domain.State) []string {
	prompt := fmt.Sprintf(`You are a software factory automation agent operating in a restricted workspace sandbox.
You must respond ONLY with a single JSON block. Do not include conversational markdown text or code fences (like `+"`"+`json or `+"`"+`) outside the JSON.

You are acting as the %s Agent in the Context Gathering phase.
Your objective is to inspect the workspace files and directories to gather necessary context before writing any code or tests.

Task Details:
Title: %s
Description: %s

Below is a list of target files for this task:
%v

You may call the following inspection tools:
- read_file: read the contents of a file. Args: {"path": "relative/path/to/file"}
- list_directory: list directory contents. Args: {"path": "relative/path/to/dir"}
- find_files: search for files. Args: {"pattern": "*.py"}
- grep_search: search for a pattern in files. Args: {"query": "search_term"}
- noop: call this if you have enough context and do not need to read any more files.

Return format:
{
  "reasoning": "Explain what context you need to gather",
  "actions": [
    {
      "tool": "read_file",
      "args": {
        "path": "frontpunch/existing_file.py"
      }
    }
  ]
}
`, role, task.Title, task.Description, task.TargetFiles)

	resp, err := o.llmClient.Complete(ctx, prompt)
	if err != nil {
		fmt.Printf("Orchestrator: Reader Phase LLM completion failed for role %s: %v. Continuing without extra context.\n", role, err)
		return nil
	}

	var gatheredContext []string
	for _, action := range resp.Actions {
		if action.Tool == "noop" {
			continue
		}
		if action.Tool != "read_file" && action.Tool != "list_directory" && action.Tool != "find_files" && action.Tool != "grep_search" {
			continue
		}
		tool, ok := o.registry.Get(action.Tool)
		if ok {
			out, err := tool.Execute(ctx, state, action.Args)
			if err == nil {
				summary := out
				if len(summary) > 2000 {
					summary = summary[:2000] + "\n... [TRUNCATED] ..."
				}
				gatheredContext = append(gatheredContext, fmt.Sprintf("Inspection result of calling %s with args %+v:\n```\n%s\n```", action.Tool, action.Args, summary))
			}
		}
	}
	return gatheredContext
}

// RunTesterAgent runs the test writer agent for the task
func (o *Orchestrator) RunTesterAgent(ctx context.Context, task domain.Task, state *domain.State, fileContexts []string) {
	// Reader Phase: collect inspection context first! (Requirement 5)
	readerContexts := o.RunReaderPhase(ctx, "tester", task, state)

	testPrompt := fmt.Sprintf("Write tests for task: %s - %s", task.Title, task.Description)
	var promptContext []string
	if len(fileContexts) > 0 {
		promptContext = append(promptContext, fmt.Sprintf("Existing files context:\n%s", strings.Join(fileContexts, "\n\n")))
	}
	if len(readerContexts) > 0 {
		promptContext = append(promptContext, fmt.Sprintf("Inspection context gathered:\n%s", strings.Join(readerContexts, "\n\n")))
	}
	if len(promptContext) > 0 {
		testPrompt = fmt.Sprintf("Write tests for task: %s - %s\n\n%s", task.Title, task.Description, strings.Join(promptContext, "\n\n"))
	}

	testerCtx := context.WithValue(ctx, AgentRoleKey, "tester")
	testResp, err := o.llmClient.Complete(testerCtx, testPrompt)
	if err == nil {
		fmt.Printf("Orchestrator: Task %s Tester LLM reasoning: %s\n", task.ID, testResp.Reasoning)
		for _, action := range testResp.Actions {
			fmt.Printf("Orchestrator: Task %s Tester LLM action: tool=%s args=%+v\n", task.ID, action.Tool, action.Args)
			domainAction := domain.Action{
				Tool: action.Tool,
				Args: action.Args,
			}
			valRes, valErr := o.validator.Validate(testerCtx, domainAction, state)
			if valErr != nil || (valRes != nil && !valRes.Allowed) {
				fmt.Fprintf(os.Stderr, "Orchestrator: Task %s tester action %s validation failed\n", task.ID, action.Tool)
				continue
			}

			tool, ok := o.registry.Get(action.Tool)
			if ok {
				_, _ = tool.Execute(testerCtx, state, action.Args)
			}
		}
	} else {
		fmt.Fprintf(os.Stderr, "Orchestrator: Task %s Tester LLM completion failed: %v\n", task.ID, err)
	}
}

// RunGeneratorAgent runs the generator agent to implement task functionality
func (o *Orchestrator) RunGeneratorAgent(ctx context.Context, task domain.Task, state *domain.State, fileContexts []string, recentTestsContext string) {
	// Reader Phase: collect inspection context first! (Requirement 5)
	readerContexts := o.RunReaderPhase(ctx, "generator", task, state)

	genPrompt := fmt.Sprintf("Execute task: %s - %s", task.Title, task.Description)
	var promptContext []string
	if len(fileContexts) > 0 {
		promptContext = append(promptContext, fmt.Sprintf("Existing files context:\n%s", strings.Join(fileContexts, "\n\n")))
	}
	if len(readerContexts) > 0 {
		promptContext = append(promptContext, fmt.Sprintf("Inspection context gathered:\n%s", strings.Join(readerContexts, "\n\n")))
	}
	if recentTestsContext != "" {
		promptContext = append(promptContext, recentTestsContext)
	}
	// Add previous failure context if retrying (Requirement 7)
	if task.Retries > 0 && task.FailureLog != "" {
		promptContext = append(promptContext, fmt.Sprintf("Previous implementation attempt FAILED. Test/Linter output:\n```\n%s\n```\nFix the code to address these errors.", task.FailureLog))
	}

	if len(promptContext) > 0 {
		genPrompt = fmt.Sprintf("Execute task: %s - %s\n\n%s", task.Title, task.Description, strings.Join(promptContext, "\n\n"))
	}

	genCtx := context.WithValue(ctx, AgentRoleKey, "generator")
	resp, err := o.llmClient.Complete(genCtx, genPrompt)
	if err == nil {
		fmt.Printf("Orchestrator: Task %s LLM reasoning: %s\n", task.ID, resp.Reasoning)
		for _, action := range resp.Actions {
			fmt.Printf("Orchestrator: Task %s LLM action: tool=%s args=%+v\n", task.ID, action.Tool, action.Args)
			domainAction := domain.Action{
				Tool: action.Tool,
				Args: action.Args,
			}
			valRes, valErr := o.validator.Validate(genCtx, domainAction, state)
			if valErr != nil || (valRes != nil && !valRes.Allowed) {
				fmt.Fprintf(os.Stderr, "Orchestrator: Task %s action %s validation failed\n", task.ID, action.Tool)
				continue
			}

			tool, ok := o.registry.Get(action.Tool)
			if ok {
				_, _ = tool.Execute(genCtx, state, action.Args)
			}
		}
	} else {
		fmt.Fprintf(os.Stderr, "Orchestrator: Task %s Generator LLM completion failed: %v\n", task.ID, err)
	}
}
