CREATE TABLE IF NOT EXISTS stories (
    id TEXT PRIMARY KEY,
    state_id TEXT NOT NULL,
    title TEXT NOT NULL,
    file_path TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    tokens_used BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY(state_id) REFERENCES state(id) ON DELETE CASCADE
);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS story_id TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE token_usage ADD COLUMN IF NOT EXISTS story_id TEXT DEFAULT '';
ALTER TABLE token_usage ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT '';
ALTER TABLE token_usage ADD COLUMN IF NOT EXISTS model TEXT DEFAULT '';
ALTER TABLE actions ADD COLUMN IF NOT EXISTS story_id TEXT DEFAULT '';
