package services

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/diegojromerolopez/noctifab/pkg/domain"
)

// ValidatePlannedTasks checks if the Planner Agent provided enough task details
func ValidatePlannedTasks(tasks []domain.Task) error {
	if len(tasks) == 0 {
		return fmt.Errorf("planning failed: no tasks were generated by the planner agent")
	}
	for i := range tasks {
		task := &tasks[i]
		if task.Title == "" || len(task.Description) < 15 {
			return fmt.Errorf("planning failed: task '%s' ('%s') does not have a detailed title or description", task.ID, task.Title)
		}
		if len(task.TargetFiles) == 0 {
			task.TargetFiles = []string{".gitignore"}
		}
	}
	return nil
}

func (o *Orchestrator) registerAgentStart(ctx context.Context, role string, taskID string) {
	agentID := fmt.Sprintf("agent-%s-%s", role, taskID)
	name := fmt.Sprintf("%s-%s", role, taskID)
	_ = o.updateStateWithRetry(ctx, func(st *domain.State) error {
		found := false
		for i := range st.ActiveAgents {
			if st.ActiveAgents[i].ID == agentID {
				st.ActiveAgents[i].Status = domain.AgentWorking
				st.ActiveAgents[i].TaskID = taskID
				st.ActiveAgents[i].StartedAt = time.Now()
				st.ActiveAgents[i].CompletedAt = time.Time{}
				found = true
				break
			}
		}
		if !found {
			st.ActiveAgents = append(st.ActiveAgents, domain.Agent{
				ID:        agentID,
				Name:      name,
				Role:      domain.AgentRole(strings.ToUpper(role)),
				Status:    domain.AgentWorking,
				TaskID:    taskID,
				StartedAt: time.Now(),
			})
		}
		return nil
	})
}

func (o *Orchestrator) registerAgentComplete(ctx context.Context, role string, taskID string, err error) {
	agentID := fmt.Sprintf("agent-%s-%s", role, taskID)
	_ = o.updateStateWithRetry(ctx, func(st *domain.State) error {
		for i := range st.ActiveAgents {
			if st.ActiveAgents[i].ID == agentID {
				st.ActiveAgents[i].Status = domain.AgentCompleted
				st.ActiveAgents[i].CompletedAt = time.Now()
				if err != nil {
					st.ActiveAgents[i].LastError = err.Error()
				} else {
					st.ActiveAgents[i].LastError = ""
				}
				break
			}
		}
		return nil
	})
}

// RunReaderPhase runs the pre-step to collect workspace context before execution
func (o *Orchestrator) RunReaderPhase(ctx context.Context, role string, task domain.Task, state *domain.State) []string {
	var availableFilesMsg string
	if files, err := o.git.Run(ctx, false, "ls-files"); err == nil {
		availableFilesMsg = fmt.Sprintf("\nBelow is a list of all existing files in the repository:\n%s\n", strings.TrimSpace(files))
	}

	prompt := fmt.Sprintf(`You are a software factory automation agent operating in a restricted workspace sandbox.
You must respond ONLY with a single JSON block. Do not include conversational markdown text or code fences (like `+"`"+`json or `+"`"+`) outside the JSON.

You are acting as the %s Agent in the Context Gathering phase.
Your objective is to inspect the workspace files and directories to gather necessary context before writing any code or tests.

Task Details:
Title: %s
Description: %s

Below is a list of target files for this task:
%v
%s
You may call the following inspection tools:
- read_file: read the contents of a file. Args: {"path": "relative/path/to/file"}
- list_directory: list directory contents. Args: {"path": "relative/path/to/dir"}
- find_files: search for files. Args: {"pattern": "*.py"}
- grep_search: search for a pattern in files. Args: {"query": "search_term"}
- noop: call this if you have enough context and do not need to read any more files.

Return format:
{
  "reasoning": "Explain what context you need to gather",
  "actions": [
    {
      "tool": "read_file",
      "args": {
        "path": "frontpunch/existing_file.py"
      }
    }
  ]
}
`, role, task.Title, task.Description, task.TargetFiles, availableFilesMsg)

	resp, err := o.llmClient.Complete(ctx, prompt)
	if err != nil {
		fmt.Printf("Orchestrator: Task [Reader] phase failed for role %s: %v. Continuing without extra context.\n", role, err)
		return nil
	}
	fmt.Printf("Orchestrator: [Reader] phase ok for role %s: actions=%d\n", role, len(resp.Actions))

	var gatheredContext []string
	for _, action := range resp.Actions {
		if action.Tool == "noop" {
			continue
		}
		if action.Tool != "read_file" && action.Tool != "list_directory" && action.Tool != "find_files" && action.Tool != "grep_search" {
			continue
		}
		tool, ok := o.registry.Get(action.Tool)
		if ok {
			out, err := tool.Execute(ctx, state, action.Args)
			if err == nil {
				summary := out
				if len(summary) > 2000 {
					summary = summary[:2000] + "\n... [TRUNCATED] ..."
				}
				gatheredContext = append(gatheredContext, fmt.Sprintf("Inspection result of calling %s with args %+v:\n```\n%s\n```", action.Tool, action.Args, summary))
			}
		}
	}
	return gatheredContext
}

// RunTesterAgent runs the test writer agent for the task
func (o *Orchestrator) RunTesterAgent(ctx context.Context, task domain.Task, state *domain.State, fileContexts []string, customPrompt string) {
	// Reader Phase: collect inspection context first! (Requirement 5)
	readerContexts := o.RunReaderPhase(ctx, "tester", task, state)

	testPrompt := customPrompt
	var promptContext []string
	if len(fileContexts) > 0 {
		promptContext = append(promptContext, fmt.Sprintf("Existing files context:\n%s", strings.Join(fileContexts, "\n\n")))
	}
	if len(readerContexts) > 0 {
		promptContext = append(promptContext, fmt.Sprintf("Inspection context gathered:\n%s", strings.Join(readerContexts, "\n\n")))
	}
	if task.Retries > 0 && task.FailureLog != "" {
		warning := "WARNING: The previous implementation/refactoring changes have been reset to the clean base commit state (minimal implementation + tests). You must re-apply all your changes from previous tries along with your new fixes. Do not assume your previous modifications persist in the files."
		summary := summarizeFailureLog(task.FailureLog)
		promptContext = append(promptContext, fmt.Sprintf("%s\n\nPrevious implementation attempt FAILED. Key failure details from the test run:\n%s\n\nFix the tests to address these specific errors.", warning, summary))
	}
	if len(promptContext) > 0 {
		testPrompt = fmt.Sprintf("%s\n\n%s", customPrompt, strings.Join(promptContext, "\n\n"))
	}

	testerCtx := context.WithValue(ctx, AgentRoleKey, "tester")
	o.registerAgentStart(ctx, "tester", task.ID)
	testResp, err := o.llmClient.Complete(testerCtx, testPrompt)
	o.registerAgentComplete(ctx, "tester", task.ID, err)
	if err == nil {
		fmt.Printf("Orchestrator: Task %s [Tester] write phase ok: reasoning=%q actions=%d\n", task.ID, testResp.Reasoning, len(testResp.Actions))
		executed := 0
		blocked := 0
		for _, action := range testResp.Actions {
			fmt.Printf("Orchestrator: Task %s [Tester] action: tool=%s args=%+v\n", task.ID, action.Tool, action.Args)
			domainAction := domain.Action{
				Tool: action.Tool,
				Args: action.Args,
			}
			valRes, valErr := o.validator.Validate(testerCtx, domainAction, state)
			if valErr != nil || (valRes != nil && !valRes.Allowed) {
				blocked++
				reason := ""
				if valRes != nil {
					reason = valRes.Reason
				}
				fmt.Fprintf(os.Stderr, "Orchestrator: Task %s [Tester] action %s blocked: %s\n", task.ID, action.Tool, reason)
				continue
			}

			tool, ok := o.registry.Get(action.Tool)
			if ok {
				_, _ = tool.Execute(testerCtx, state, action.Args)
				executed++
			}
		}
		fmt.Printf("Orchestrator: Task %s [Tester] write phase summary: %d executed, %d blocked\n", task.ID, executed, blocked)
	} else {
		fmt.Fprintf(os.Stderr, "Orchestrator: Task %s [Tester] write phase failed: %v\n", task.ID, err)
	}
}

// RunGeneratorAgent runs the generator agent to implement task functionality
func (o *Orchestrator) RunGeneratorAgent(ctx context.Context, task domain.Task, state *domain.State, fileContexts []string, recentTestsContext string, customPrompt string) {
	// Reader Phase: collect inspection context first! (Requirement 5)
	readerContexts := o.RunReaderPhase(ctx, "generator", task, state)

	genPrompt := customPrompt
	var promptContext []string
	if len(fileContexts) > 0 {
		promptContext = append(promptContext, fmt.Sprintf("Existing files context:\n%s", strings.Join(fileContexts, "\n\n")))
	}
	if len(readerContexts) > 0 {
		promptContext = append(promptContext, fmt.Sprintf("Inspection context gathered:\n%s", strings.Join(readerContexts, "\n\n")))
	}
	if recentTestsContext != "" {
		promptContext = append(promptContext, recentTestsContext)
	}
	// Add previous failure context if retrying (Requirement 7)
	if task.Retries > 0 && task.FailureLog != "" {
		warning := "WARNING: The previous implementation/refactoring changes have been reset to the clean base commit state (minimal implementation + tests). You must re-apply all your changes from previous tries along with your new fixes. Do not assume your previous modifications persist in the files."
		summary := summarizeFailureLog(task.FailureLog)
		promptContext = append(promptContext, fmt.Sprintf("%s\n\nPrevious implementation attempt FAILED. Key failure details from the test run:\n%s\n\nFix the code to address these specific errors.", warning, summary))
	}

	if len(promptContext) > 0 {
		genPrompt = fmt.Sprintf("%s\n\n%s", customPrompt, strings.Join(promptContext, "\n\n"))
	}

	genCtx := context.WithValue(ctx, AgentRoleKey, "generator")
	o.registerAgentStart(ctx, "generator", task.ID)
	resp, err := o.llmClient.Complete(genCtx, genPrompt)
	o.registerAgentComplete(ctx, "generator", task.ID, err)
	if err == nil {
		fmt.Printf("Orchestrator: Task %s [Generator] write phase ok: reasoning=%q actions=%d\n", task.ID, resp.Reasoning, len(resp.Actions))
		executed := 0
		blocked := 0
		for _, action := range resp.Actions {
			fmt.Printf("Orchestrator: Task %s [Generator] action: tool=%s args=%+v\n", task.ID, action.Tool, action.Args)
			domainAction := domain.Action{
				Tool: action.Tool,
				Args: action.Args,
			}
			valRes, valErr := o.validator.Validate(genCtx, domainAction, state)
			if valErr != nil || (valRes != nil && !valRes.Allowed) {
				blocked++
				reason := ""
				if valRes != nil {
					reason = valRes.Reason
				}
				fmt.Fprintf(os.Stderr, "Orchestrator: Task %s [Generator] action %s blocked: %s\n", task.ID, action.Tool, reason)
				continue
			}

			tool, ok := o.registry.Get(action.Tool)
			if ok {
				_, _ = tool.Execute(genCtx, state, action.Args)
				executed++
			}

			if action.Tool == "request_test_fix" {
				feedback, _ := action.Args["feedback"].(string)
				fmt.Printf("Orchestrator: Task %s [Generator] requested test fix: %s\n", task.ID, feedback)

				testerPrompt := fmt.Sprintf("Fix the tests for task: %s - %s\n\nFeedback from generator agent:\n%s\n\nCorrect the test files to resolve this issue.", task.Title, task.Description, feedback)
				o.RunTesterAgent(ctx, task, state, fileContexts, testerPrompt)

				// Stage and commit test fixes
				statusOut, _ := o.git.Run(ctx, false, "status", "--porcelain")
				if strings.TrimSpace(statusOut) != "" {
					_, _ = o.git.Run(ctx, true, "add", "--all", "--", ":!.noctifab")
					stagedOut, _ := o.git.Run(ctx, false, "diff", "--cached", "--name-only")
					if strings.TrimSpace(stagedOut) != "" {
						commitMsg := fmt.Sprintf("test(core): fix tests for task %s - %s (requested by generator)", task.ID, task.Title)
						_, commitErr := o.git.Run(ctx, true, "commit", "-m", commitMsg)
						if commitErr != nil {
							fmt.Fprintf(os.Stderr, "Orchestrator: Git commit failed for task %s test fixes: %v\n", task.ID, commitErr)
						}
					}
				}
			}
		}
		fmt.Printf("Orchestrator: Task %s [Generator] write phase summary: %d executed, %d blocked\n", task.ID, executed, blocked)
	} else {
		fmt.Fprintf(os.Stderr, "Orchestrator: Task %s [Generator] write phase failed: %v\n", task.ID, err)
	}
}

func summarizeFailureLog(log string) string {
	lines := strings.Split(log, "\n")
	var importantLines []string
	capture := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "ERROR:") || strings.HasPrefix(trimmed, "FAIL:") {
			capture = true
		}
		if capture {
			importantLines = append(importantLines, line)
		} else if strings.Contains(line, "Error:") || strings.Contains(line, "Exception") || strings.Contains(line, "FAILED") {
			importantLines = append(importantLines, line)
		}
	}

	if len(importantLines) == 0 {
		// Fallback to last 15 lines if no specific failures are captured
		start := len(lines) - 15
		if start < 0 {
			start = 0
		}
		return strings.Join(lines[start:], "\n")
	}

	return strings.Join(importantLines, "\n")
}
