package services

import (
	"context"
	"strings"
	"sync"

	"github.com/diegojromerolopez/noctifab/pkg/domain"
	"github.com/diegojromerolopez/noctifab/pkg/infrastructure/telemetry"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// FileLockRegistry prevents concurrent tasks from writing to overlapping files.
type FileLockRegistry struct {
	mu    sync.Mutex
	locks map[string]string // maps file path -> task ID
}

func NewFileLockRegistry() *FileLockRegistry {
	return &FileLockRegistry{
		locks: make(map[string]string),
	}
}

// TryAcquireLocks attempts to lock all target files for a given task.
// If any file is locked by another task, it rolls back and returns false.
func (r *FileLockRegistry) TryAcquireLocks(taskID string, files []string) bool {
	r.mu.Lock()
	defer r.mu.Unlock()

	// Check if any file is already locked
	for _, file := range files {
		if holder, locked := r.locks[file]; locked && holder != taskID {
			return false
		}
	}

	// Acquire locks
	for _, file := range files {
		r.locks[file] = taskID
	}
	return true
}

// ReleaseLocks releases all locks held by a task.
func (r *FileLockRegistry) ReleaseLocks(taskID string) {
	r.mu.Lock()
	defer r.mu.Unlock()

	for file, holder := range r.locks {
		if holder == taskID {
			delete(r.locks, file)
		}
	}
}

// Scheduler handles task topological checks and parallel task selection.
type Scheduler struct {
	lockRegistry *FileLockRegistry
}

func NewScheduler(registry *FileLockRegistry) *Scheduler {
	return &Scheduler{
		lockRegistry: registry,
	}
}

// normalizeDependencyToken lowercases a string and strips every
// non-alphanumeric character, so minor naming variations generated by the LLM
// still resolve to the intended task.
func normalizeDependencyToken(str string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(str) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// dependencyIndex memoizes the exact and normalized ID/Title lookups for a
// task list so dependency resolution inside GetReadyTasks does not
// re-normalize every task per call (previously O(T²)–O(T³)).
type dependencyIndex struct {
	exact      map[string]string // ID or Title -> task ID (first task wins)
	normalized map[string]string // normalized ID or Title -> task ID (first task wins)
	entries    []dependencyIndexEntry
}

type dependencyIndexEntry struct {
	id        string
	normID    string
	normTitle string
}

// newDependencyIndex builds the resolution index once for a set of tasks.
func newDependencyIndex(tasks []domain.Task) *dependencyIndex {
	idx := &dependencyIndex{
		exact:      make(map[string]string, len(tasks)*2),
		normalized: make(map[string]string, len(tasks)*2),
		entries:    make([]dependencyIndexEntry, 0, len(tasks)),
	}
	for _, t := range tasks {
		if _, ok := idx.exact[t.ID]; !ok {
			idx.exact[t.ID] = t.ID
		}
		if _, ok := idx.exact[t.Title]; !ok {
			idx.exact[t.Title] = t.ID
		}
		normID := normalizeDependencyToken(t.ID)
		normTitle := normalizeDependencyToken(t.Title)
		if normID != "" {
			if _, ok := idx.normalized[normID]; !ok {
				idx.normalized[normID] = t.ID
			}
		}
		if normTitle != "" {
			if _, ok := idx.normalized[normTitle]; !ok {
				idx.normalized[normTitle] = t.ID
			}
		}
		idx.entries = append(idx.entries, dependencyIndexEntry{id: t.ID, normID: normID, normTitle: normTitle})
	}
	return idx
}

// resolve maps a dependency string (which might be an ID or Title) to the
// corresponding task ID, using exact matching first, then normalized matching
// (case-insensitive, ignoring non-alphanumeric characters), and finally a
// substring/prefix fallback — preserving the historical resolution semantics.
func (idx *dependencyIndex) resolve(dep string) (string, bool) {
	// 1. Exact ID or Title match
	if id, ok := idx.exact[dep]; ok {
		return id, true
	}

	normDep := normalizeDependencyToken(dep)
	if normDep == "" {
		return "", false
	}

	// 2. Exact normalized match
	if id, ok := idx.normalized[normDep]; ok {
		return id, true
	}

	// 3. Substring / Prefix match
	for _, e := range idx.entries {
		if strings.Contains(e.normTitle, normDep) || strings.Contains(normDep, e.normTitle) ||
			strings.Contains(e.normID, normDep) || strings.Contains(normDep, e.normID) {
			return e.id, true
		}
	}

	return "", false
}

// GetReadyTasks returns tasks that are PENDING or FAILED (eligible for retry)
// and whose upstream dependencies are all SUCCESS, respecting file locks and agent concurrency.
func (s *Scheduler) GetReadyTasks(state *domain.State, concurrencyLimit int) []domain.Task {
	_, span := telemetry.Tracer().Start(context.Background(), "GetReadyTasks",
		trace.WithAttributes(
			attribute.Int("concurrency_limit", concurrencyLimit),
			attribute.Int("task_count", len(state.Tasks)),
		))
	defer span.End()

	// Build map of task ID to status
	statusMap := make(map[string]domain.TaskStatus)
	for _, t := range state.Tasks {
		statusMap[t.ID] = t.Status
	}

	// Build the dependency resolution index once per invocation.
	depIndex := newDependencyIndex(state.Tasks)

	// Compute blocked tasks transitively from unresolved clarifications
	blocked := make(map[string]bool)
	for _, c := range state.Clarifications {
		if !c.Resolved {
			if c.TaskID == "" {
				// Global clarification blocks everything
				return nil
			}
			blocked[c.TaskID] = true
			if resolvedID, found := depIndex.resolve(c.TaskID); found {
				blocked[resolvedID] = true
			}
		}
	}

	// Propagate blocks downstream (iteratively)
	changed := true
	for changed {
		changed = false
		for _, t := range state.Tasks {
			if blocked[t.ID] {
				continue
			}
			for _, dep := range t.DependsOn {
				depID := dep
				if resolvedID, found := depIndex.resolve(dep); found {
					depID = resolvedID
				}
				if blocked[depID] {
					blocked[t.ID] = true
					changed = true
					break
				}
			}
		}
	}

	// Count active agents
	activeCount := 0
	for _, agent := range state.ActiveAgents {
		if agent.Status == domain.AgentWorking {
			activeCount++
		}
	}

	availableSlots := concurrencyLimit - activeCount
	if availableSlots <= 0 {
		return nil
	}

	var ready []domain.Task
	for i, t := range state.Tasks {
		if t.Status != domain.TaskPending && t.Status != domain.TaskFailed {
			continue
		}

		// Check if max retries reached
		if t.Status == domain.TaskFailed && t.Retries >= t.MaxRetries {
			continue
		}

		// Skip if transitively blocked by unresolved clarification
		if blocked[t.ID] {
			continue
		}

		// Check dependencies
		depsMet := true
		for _, dep := range t.DependsOn {
			depID := dep
			if resolvedID, found := depIndex.resolve(dep); found {
				depID = resolvedID
			}
			status, ok := statusMap[depID]
			if !ok || status != domain.TaskSuccess {
				depsMet = false
				break
			}
		}

		// Story Completion Milestone Barrier:
		// Ensure tasks belonging to a downstream story (e.g. US-002) do not execute
		// until all tasks belonging to earlier upstream stories (e.g. US-001) have reached TaskSuccess.
		if depsMet && t.StoryID != "" {
			tStoryIndex := parseStoryIndex(t.StoryID)
			if tStoryIndex > 0 {
				for _, other := range state.Tasks {
					if other.StoryID != "" && other.ID != t.ID {
						otherStoryIndex := parseStoryIndex(other.StoryID)
						if otherStoryIndex > 0 && otherStoryIndex < tStoryIndex {
							if other.Status != domain.TaskSuccess {
								depsMet = false
								break
							}
						}
					}
				}
			}
		}

		if depsMet {
			// Check file locks
			if s.lockRegistry.TryAcquireLocks(t.ID, t.TargetFiles) {
				ready = append(ready, state.Tasks[i])
				if len(ready) >= availableSlots {
					break
				}
			}
		}
	}

	return ready
}

func (s *Scheduler) ReleaseLocks(taskID string) {
	s.lockRegistry.ReleaseLocks(taskID)
}

func parseStoryIndex(storyID string) int {
	if storyID == "" {
		return 0
	}
	var num int
	for _, r := range storyID {
		if r >= '0' && r <= '9' {
			num = num*10 + int(r-'0')
		}
	}
	return num
}
