package services

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/diegojromerolopez/noctifab/pkg/domain"
)

// ValidatePlannedTasks checks if the Planner Agent provided enough task details, enforces cohesion, and resolves dependencies
func ValidatePlannedTasks(tasks []domain.Task, projectPath ...string) error {
	if len(tasks) == 0 {
		return fmt.Errorf("planning failed: no tasks were generated by the planner agent")
	}
	path := "."
	if len(projectPath) > 0 && projectPath[0] != "" {
		path = projectPath[0]
	}
	for i := range tasks {
		task := &tasks[i]
		if task.Title == "" || len(task.Description) < 15 {
			return fmt.Errorf("planning failed: task '%s' ('%s') does not have a detailed title or description", task.ID, task.Title)
		}
		if len(task.TargetFiles) == 0 {
			task.TargetFiles = []string{".gitignore"}
		}
	}
	resolved, err := ResolveTaskDependencies(tasks, path)
	if err != nil {
		return fmt.Errorf("planning failed: %w", err)
	}
	for i := range tasks {
		tasks[i].DependsOn = resolved[i].DependsOn
	}
	if _, err := ResolveAndSortTasks(tasks); err != nil {
		return fmt.Errorf("planning failed: %w", err)
	}
	if err := ValidateTaskCohesion(tasks); err != nil {
		return fmt.Errorf("planning failed: %w", err)
	}
	return nil
}

// ResolveTaskDependencies validates and resolves dependency identifiers in a planned task DAG.
// Intra-story dependencies matching other task IDs/titles in the DAG are preserved.
// Cross-story dependencies matching valid, existing user story files (e.g., US-001) are marked as satisfied and removed.
// Dependencies referencing non-existent tasks or story files return a descriptive error.
func ResolveTaskDependencies(tasks []domain.Task, projectPath string) ([]domain.Task, error) {
	if len(tasks) == 0 {
		return tasks, nil
	}

	// Build lookup set of current DAG task IDs and titles
	existingTaskIDs := make(map[string]bool)
	for _, t := range tasks {
		if t.ID != "" {
			existingTaskIDs[t.ID] = true
		}
		if t.Title != "" {
			existingTaskIDs[t.Title] = true
		}
	}

	resolvedTasks := make([]domain.Task, len(tasks))
	copy(resolvedTasks, tasks)

	for i := range resolvedTasks {
		task := &resolvedTasks[i]
		var cleanDeps []string

		for _, dep := range task.DependsOn {
			depClean := strings.TrimSpace(dep)
			if depClean == "" {
				continue
			}

			// 1. Direct match with a task in the current DAG
			if existingTaskIDs[depClean] {
				cleanDeps = append(cleanDeps, depClean)
				continue
			}

			// 2. Check if dependency is a valid cross-story task reference (e.g., "US-001-TASK-001")
			if isTaskReference(depClean) {
				storyID := ExtractStoryID(depClean)
				if storyID != "" && storyExists(projectPath, storyID) {
					cleanDeps = append(cleanDeps, depClean)
					continue
				}
			}

			// 3. Check if dependency is a user story reference (e.g., "US-001", "US-001.md", "roadmap/US-001.md")
			if isStoryReference(depClean) {
				if storyExists(projectPath, depClean) {
					// Referenced user story exists; prerequisite is satisfied. Omit from active task DAG dependencies.
					continue
				}
				fmt.Fprintf(os.Stderr, "⚠ Warning: pruning non-existent user story dependency %q from task %q (%s)\n", depClean, task.ID, task.Title)
				continue
			}

			// 4. Dependency is neither a current task nor a valid story file (LLM hallucination)
			fmt.Fprintf(os.Stderr, "⚠ Warning: pruning unknown/hallucinated task dependency %q from task %q (%s)\n", depClean, task.ID, task.Title)
		}

		task.DependsOn = cleanDeps
	}

	// Auto-serialize tasks that declare overlapping target files or root build configurations
	fileLastTaskID := make(map[string]string)
	for i := range resolvedTasks {
		task := &resolvedTasks[i]
		for _, tf := range task.TargetFiles {
			cleanFile := strings.ToLower(filepath.Clean(strings.TrimSpace(tf)))
			if !IsSharedRootBuildFile(cleanFile) {
				continue
			}
			if prevTaskID, exists := fileLastTaskID[cleanFile]; exists && prevTaskID != task.ID {
				hasDep := false
				for _, d := range task.DependsOn {
					if d == prevTaskID {
						hasDep = true
						break
					}
				}
				if !hasDep {
					task.DependsOn = append(task.DependsOn, prevTaskID)
				}
			}
			fileLastTaskID[cleanFile] = task.ID
		}
	}

	return resolvedTasks, nil
}

var sharedRootBuildFiles = map[string]bool{
	"makefile":          true,
	"gnumakefile":       true,
	"cmakelists.txt":    true,
	"pyproject.toml":    true,
	"setup.py":          true,
	"setup.cfg":         true,
	"package.json":      true,
	"package-lock.json": true,
	"yarn.lock":         true,
	"pnpm-lock.yaml":    true,
	"cargo.toml":        true,
	"cargo.lock":        true,
	"go.mod":            true,
	"go.sum":            true,
	"pom.xml":           true,
	"build.gradle":      true,
	"build.gradle.kts":  true,
}

// IsSharedRootBuildFile checks whether the path corresponds to a shared root build/project manifest.
func IsSharedRootBuildFile(path string) bool {
	clean := strings.ToLower(filepath.Clean(strings.TrimSpace(path)))
	if strings.Contains(clean, "/") || strings.Contains(clean, "\\") {
		dir := filepath.Dir(clean)
		if dir != "." && dir != "" {
			return false
		}
		clean = filepath.Base(clean)
	}
	return sharedRootBuildFiles[clean]
}

// isTaskReference checks if a dependency string looks like a task identifier (e.g. "US-001-TASK-001", "TASK-001", "task-1").
func isTaskReference(dep string) bool {
	upper := strings.ToUpper(strings.TrimSpace(dep))
	return strings.Contains(upper, "-TASK-") ||
		strings.Contains(upper, "TASK-") ||
		strings.HasPrefix(upper, "TASK-")
}

// isStoryReference checks if a dependency string looks like a user story identifier.
func isStoryReference(dep string) bool {
	if isTaskReference(dep) {
		return false
	}
	upper := strings.ToUpper(dep)
	return strings.HasPrefix(upper, "US-") ||
		strings.Contains(upper, "US-") ||
		strings.HasPrefix(strings.ToLower(dep), "roadmap/")
}

// storyExists checks if the specified user story exists on disk relative to projectPath.
func storyExists(projectPath, dep string) bool {
	clean := strings.TrimSpace(dep)
	candidates := []string{
		clean,
		clean + ".md",
		filepath.Join("roadmap", "user-stories", clean),
		filepath.Join("roadmap", "user-stories", clean+".md"),
	}

	for _, cand := range candidates {
		absPath := cand
		if !filepath.IsAbs(cand) {
			absPath = filepath.Join(projectPath, cand)
		}
		info, err := os.Stat(absPath)
		if err == nil && !info.IsDir() {
			return true
		}
	}

	// Also check glob patterns for slugged story files (e.g. US-001-*.md) under roadmap/user-stories
	base := strings.TrimSuffix(filepath.Base(clean), ".md")
	if matches, err := filepath.Glob(filepath.Join(projectPath, "roadmap", "user-stories", base+"*.md")); err == nil && len(matches) > 0 {
		return true
	}

	return false
}
