name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run Tests
        run: |
          go test -v ./pkg/... ./cmd/...

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2

  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run E2E Tests
        run: |
          docker compose -f tests/e2e/docker-compose.yml up --build --exit-code-from test-runner
